/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolrn;

import javafx.scene.paint.Color;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class GUI extends javax.swing.JFrame {
    
    private ArbolRN arbol = new ArbolRN();
    private NodoRN nodo, padre, hijo;
    private JLabel[] label = new JLabel[100];
    private int x;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        GridsCanvas xyz = new GridsCanvas(800, 400, 10, 10);
        add(xyz);
        arbol.inicializar();
        this.x=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonDibujar = new javax.swing.JButton();
        jButtonRetirar = new javax.swing.JButton();
        jButtonInsertar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Árbol Rojinegro");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jButtonDibujar.setText("Dibujar");
        jButtonDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDibujarActionPerformed(evt);
            }
        });

        jButtonRetirar.setText("Retirar");
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite número a insertar o retirar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jButtonInsertar)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetirar)
                .addGap(18, 18, 18)
                .addComponent(jButtonDibujar)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDibujar)
                    .addComponent(jButtonRetirar)
                    .addComponent(jButtonInsertar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDibujarActionPerformed
        //limpia();
        //paint();
    }//GEN-LAST:event_jButtonDibujarActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        arbol.insertar(Integer.parseInt(jTextField1.getText()));
        arbol.inorden(arbol.Raiz());
        System.out.println("");
        arbol.preorden(arbol.Raiz());
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        arbol.eliminar(arbol.Raiz(), Integer.parseInt(jTextField1.getText()));
        arbol.inorden(arbol.Raiz());
        System.out.println("");
        arbol.preorden(arbol.Raiz());
    }//GEN-LAST:event_jButtonRetirarActionPerformed
    /*public void paint(){
        int nivel = 0;
        
        label[x] = new JLabel();
        nodo =arbol.Raiz().getDer();
        System.out.println("La raiz es.."+nodo.getLlave());
        label[x].setText(Integer.toString(nodo.getLlave()));
        if(nodo.getColor()==0){
            label[x].setBackground(java.awt.Color.BLACK);
        }else{
            label[x].setBackground(java.awt.Color.red);
        }
        label[x].setBounds(380, 20, 20, 20);
        jPanel1.add(label[x]);
        this.x++;
        while (nodo.getDer() != null && nodo.getIzq() != null) {
            nivel++;
            padre = nodo;
            nodo = nodo.getIzq();
            if (nodo != null) {
                label[x] = new JLabel();
                if (nodo.getColor() == 0) {
                    label[x].setBackground(java.awt.Color.BLACK);
                } else {
                    label[x].setBackground(java.awt.Color.red);
                }
                label[x].setBounds(170, 40, 20, 20);
                jPanel1.add(label[x]);
                this.x++;
            }else{
                label[x] = new JLabel();
                if (nodo.getColor() == 0) {
                    label[x].setBackground(java.awt.Color.BLACK);
                } else {
                    label[x].setBackground(java.awt.Color.red);
                }
                label[x].setBounds(170, 40, 20, 20);
                jPanel1.add(label[x]);
                this.x++;
            }
        }
        add(jPanel1);
        setVisible(true);
        repaint();
    }
    public void limpia(){
        jPanel1.removeAll();
        //jPanel1.revalidate();
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDibujar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
